- op: replace #action 
  path: /spec/template/spec/containers/0/image #resouirce we want to change
  value: ghcr.io/rateit-pm4-org/rateit-api@sha256:d41fa4b4c33924f749f28323245aa31919165888b4cbb9750bb65cbc356220da