- op: replace #action 
  path: /spec/template/spec/containers/0/image #resouirce we want to change
  value: ghcr.io/rateit-pm4-org/rateit-frontend@sha256:0f4288696481b4336a2ca22eb8c6f7bbe49a05773e687ca09f490aa17af976f8