apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
metadata:
  name: staging
resources:
  - ../base

nameSuffix: -staging

commonLabels:
  app: rateit
  env: staging

configMapGenerator:
  - name: rateit-env
    behavior: replace
    files:
      - ./env/application.properties
    literals:
      - mongo-uri=db-service-staging

images:
  - name: ghcr.io/rateit-pm4-org/rateit-api
    newName: ghcr.io/rateit-pm4-org/rateit-api
    newTag: staging

patches:
  - target:
      kind: Ingress
      labelSelector: 
        component=api
    path: api-ingress-patch.yaml