apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
metadata:
  name: production
resources:
  - ../base

nameSuffix: -production

commonLabels:
  app: rateit
  env: production

images:
  - name: ghcr.io/rateit-pm4-org/rateit-api
    newName: ghcr.io/rateit-pm4-org/rateit-api
    newTag: latest

patches:
  - target:
      kind: Ingress
      labelSelector: 
        component=api
    path: api-ingress-patch.yaml
  - target:
      kind: ConfigMap
      labelSelector: 
        app=rateit
    patch: |-
      - op: replace
        path: /data/mongo-uri
        value: db-service-production