apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
metadata:
  name: production
resources:
  - ../base

nameSuffix: -production

commonLabels:
  app: rateit
  env: production

configMapGenerator:
  - name: rateit-env
    behavior: replace
    files:
      - ./env/application.properties

patches:
  - target:
      kind: Deployment
      labelSelector: 
        component=api
    path: api-deployment-patch.yaml
  - target:
      kind: Ingress
      labelSelector: 
        component=api
    path: api-ingress-patch.yaml