version: '3.1'

name: rateit-dev
services:
  mongo:
    image: mongo:8.0.9
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: test
    ports:
      - 27017:27017

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: test
      ME_CONFIG_MONGODB_URL: mongodb://root:test@mongo:27017/
      ME_CONFIG_BASICAUTH: false

# Kann ausgeführt werden, um Dumps aus dem dumps-Ordner in die MongoDB zu importieren
  mongo-import-dump:
    image: mongo:8.0.6
    restart: "no"
    volumes:
      - ./dumps:/dumps
      - ./loadDumps.sh:/loadDumps.sh
    command: ["sh", "-c", "/loadDumps.sh"]