apiVersion: apps/v1
kind: Deployment
metadata:
  name: api
  labels:
    app: rateit
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rateit
      component: api
  strategy: {}
  template:
    metadata:
      labels:
        app: rateit
        component: api
    spec:
      containers:
      - name: api
        image: ghcr.io/rateit-pm4-org/rateit-api:stage
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
        resources: {}
        volumeMounts:
        - name: api-props
          mountPath: /config
      volumes:
      - name: api-props
        configMap:
          name: rateit-env
          items:
          - key: application.properties
            path: application.properties


---

apiVersion: v1
kind: Service
metadata:
  name: api
  labels:
    app: rateit
spec:
  type: ClusterIP
  ports:
  - port: 80
    protocol: TCP
    targetPort: 8080
  selector:
    app: rateit
    component: api

---

apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: api-ingress
  labels:
    app: rateit
spec:
  rules:
  - host: api-rateit.pm4.init-lab.ch
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: api
            port:
              number: 80


