apiVersion: batch/v1
kind: CronJob
metadata:
  name: backup-db-cronjob
spec:
  schedule: "*/30 * * * *" # Runs backup every 30 minutes
  concurentPolicy: Replace
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: mongodump
            image: mongo:latest
            command:
            - sh
            - -c
            - |
              # Create backup directory
              mkdir -p /backup/db
              # Perform backup
              mongodump --db=rateit --authenticationDatabase=admin --host=$MONGO_HOST --port=27017 --username=$MONGO_USERNAME --password=$MONGO_PASSWORD --archive=/backup/db/$(date +\%Y-\%m-\%dT\%H-\%M-\%S).dump
              # Remove backups older than 7 days
              find /backup -type d -mtime +7 -exec rm -rf {} +
            env:
            - name: MONGO_HOST
              valueFrom:
                configMapKeyRef:
                  name: rateit-env
                  key: MONGODB_HOST
            - name: MONGO_USERNAME
              valueFrom:
                secretKeyRef:
                  name: rateit-secret
                  key: mongo-user
            - name: MONGO_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: rateit-secret
                  key: mongo-password  
            volumeMounts:
            - name: backup-storage
              mountPath: /backup
          restartPolicy: Never
          volumes:
          - name: backup-storage
            persistentVolumeClaim:
              claimName: backup-pvc