apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: db-statefulset
  labels:
    component: db
spec:
  serviceName: db-service
  replicas: 1
  selector:
    matchLabels:
      component: db
  template:
    metadata:
      labels:
        component: db
    spec:
      automountServiceAccountToken: false
      containers:
        - name: mongo-container
          image: mongo:8.0.5
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 27017
          env:
            - name: MONGO_INITDB_ROOT_USERNAME
              valueFrom:
                secretKeyRef:
                  name: rateit-secret
                  key: mongo-user
            - name: MONGO_INITDB_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: rateit-secret
                  key: mongo-password
          resources:
            limits:
              memory: 1024Mi
              cpu: 500m
              storage: 5Gi
          volumeMounts:
            - name: mongo-data
              mountPath: /data/db
      volumes:
        - name: mongo-data
          emptyDir: {}
  volumeClaimTemplates:
    - metadata:
        name: mongo-data
      spec:
        accessModes: ["ReadWriteOnce"]
        storageClassName: cinder-csi
        resources:
          requests:
            storage: 5Gi

---
apiVersion: v1
kind: Service
metadata:
  name: db-service
  labels:
    component: db
spec:
  type: ClusterIP
  clusterIP: None
  ports:
    - port: 27017
      protocol: TCP
      targetPort: 27017
  selector:
    component: db
