apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: backup-db-pvc
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: cinder-csi
  resources:
    requests:
      storage: 5Gi
---
apiVersion: batch/v1
kind: CronJob
metadata:
  name: db-backup
spec:
  schedule: "*/5 * * * *" # Runs backup every five minutes
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: mongodump
            image: mongo:latest
            command:
            - sh
            - -c
            - |
              # Perform backup
              mongodump --host=$MONGO_HOST --port=27017 --username=$MONGO_ROOT_USERNAME --password=$MONGO_ROOT_PASSWORD --out=/backup/$(date +\%Y-\%m-\%dT\%H-\%M-\%S)
              # Remove backups older than 7 days
              find /backup -type d -mtime +7 -exec rm -rf {} +
            env:
            - name: MONGO_HOST
              valueFrom:
                configMapKeyRef:
                  name: rateit-env
                  key: MONGODB_HOST
            - name: MONGO_ROOT_USERNAME
              valueFrom:
                secretKeyRef:
                  name: rateit-secret
                  key: mongo-user
            - name: MONGO_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: rateit-secret
                  key: mongo-password  
            volumeMounts:
            - name: backup-storage
              mountPath: /backup
          restartPolicy: Never
          volumes:
          - name: backup-storage
            persistentVolumeClaim:
              claimName: backup-db-pvc