apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  labels:
    app: rateit
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rateit
      component: frontend
  strategy: {}
  template:
    metadata:
      labels:
        app: rateit
        component: frontend
    spec:
      containers:
      - name: frontend
        image: ghcr.io/rateit-pm4-org/rateit-frontend:stage
        imagePullPolicy: Always
        ports:
        - containerPort: 80
        resources: {}


---

apiVersion: v1
kind: Service
metadata:
  name: frontend
  labels:
    app: rateit
spec:
  type: ClusterIP
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: rateit
    component: frontend

---

apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: frontend-ingress
  labels:
    app: rateit
spec:
  rules:
  - host: frontend-rateit.pm4.init-lab.ch
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: frontend
            port:
              number: 80


