apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
metadata:
  name: base
  labels:
    app: rateit
    env: base

resources:
- api.yaml
- db.yaml
- configMap.yaml
- secrets.yaml

labels:
  - pairs: 
    - key: app
      value: rateit
    - key: env
      value: base
    includeSelectors: true  
    includeTemplates: true
