apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
metadata:
  name: base
  labels:
    app: rateit
    env: base

resources:
- api.yaml
- db.yaml

commonLabels:
  app: rateit
  env: base

configMapGenerator:
  - name: rateit-env
    files:
      - ./env/application.properties
    literals:
      - mongo-uri=db-service

secretGenerator:
  - name: rateit-secret
    literals:
      - mongo-user=my-username
      - mongo-password=my-password