apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
metadata:
  name: base
  labels:
    app: rateit
    env: base

resources:
- api.yaml
- db.yaml
- frontend.yaml

labels:
  - pairs: 
      app: rateit
      env: base
    includeSelectors: true  
    includeTemplates: true

configMapGenerator:
  - name: rateit-env
    files:
      - ./env/application.properties

secretGenerator:
  - name: rateit-secret
    literals:
      - mongo-user=my-username
      - mongo-password=my-password