apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
metadata:
  name: base
  labels:
    app: rateit
    env: base

resources:
- api.yaml
- db.yaml
- backup_pvc.yaml
- backup_db_job.yaml
- backup_access.yaml
- frontend.yaml

labels:
  - pairs: 
      app: rateit
      env: base
    includeSelectors: true  
    includeTemplates: true

configMapGenerator:
  - name: rateit-env
    files:
      - ./env/application.properties
    literals:
      - MONGODB_HOST=db-service
      - FRONTEND_URL=https://frontend-rateit-base.pm4.init-lab.ch
