name: CI for API
on: 
  workflow_dispatch

jobs:
  build-and-push-image:
    runs-on: ubuntu-latest
    steps:
      - uses: ./.github/workflows/docker-image-build-push.yml
        with:
          imageName: rateit-api
          imageTag: latest
          dockerFilePath: api/docker/Dockerfile
          buildPath: api
