name: CI for API
on: 
  workflow_dispatch:
  workflow_call:
  push:
    branches:
      - main
      - stage
  pull_request:
    branches:
      - main
      - stage

jobs:
  java-test:
    permissions:
      checks: write
    uses: ./.github/workflows/module-java-test.yml
    with:
      projectRoot: api
