name: CI for API
on: 
  workflow_dispatch

jobs:
  build-and-push-image:
    uses: ./.github/workflows/docker-image-build-push.yml
    permissions:
      contents: read
      packages: write
      attestations: write
      id-token: write
    with:
      imageName: rateit-api
      imageTag: latest
      dockerFilePath: api/docker/Dockerfile
      buildPath: api
