name: CD for API
on: 
  workflow_dispatch:
  workflow_call:
  push:
      branches:
        - main
        - stage
      paths:
        - api/**

jobs:
  build-and-push-image:
    name: Build and Push Docker Image API
    uses: ./.github/workflows/module-docker-image-build-push.yml
    permissions:
      contents: read
      packages: write
      attestations: write
      id-token: write
    with:
      imageName: rateit-api
      imageTag: ${{ github.ref_name== 'refs/heads/main' && 'latest' || 'stage' }}
      dockerFilePath: api/docker/Dockerfile
      buildPath: api
