name: CD Production for API
on: 
  workflow_dispatch:
  workflow_call:
  push:
      branches:
        - main

jobs:
  retag-image:
    runs-on: ubuntu-latest
    permissions:
      packages: write
    steps:
      - name: Retag Image API
        uses: tinact/docker.image-retag@master
        with:
          image_name: ghcr.io/rateit-pm4-org/rateit-frontend
          image_old_tag: stage
          image_new_tag: latest
          registry: ghcr.io
          registry_username: ${{ github.actor }}
          registry_password: ${{ secrets.GITHUB_TOKEN }}
