name: CI for API
on: 
  workflow_dispatch:
  workflow_call:
  push:
    branches:
      - main
      - stage
  pull_request:
    branches:
      - main
      - stage

      
jobs:
  pre_job:
    name: Skip Check
    runs-on: ubuntu-latest
    outputs:
      should_skip: ${{ steps.skip_check.outputs.should_skip }}
    steps:
      - id: skip_check
        uses: fkirc/skip-duplicate-actions@v5
        with:
          # All of these options are optional, so you can remove them if you are happy with the defaults
          concurrent_skipping: 'never'
          paths: '["api/**"]'
  api-test:
    needs: pre_job
    name: API Test
    if: needs.pre_job.outputs.should_skip != 'true'
    permissions:
      checks: write
    uses: ./.github/workflows/module-java-test.yml
    with:
      projectRoot: api
      projectName: API
