name: CI for API
on: 
  workflow_dispatch:
  workflow_call:
  pull_request:
    branches:
      - main
      - stage


jobs:
  api-test:
    name: API Test
    permissions:
      checks: write
    uses: ./.github/workflows/module-java-test.yml
    secrets: inherit
    with:
      projectRoot: api
      projectName: API
