name: Docker Image Build/Push
on:
  workflow_dispatch:
    inputs:
      imageName:
        required: true
        type: string
      imageTag:
        required: true
        type: string
        default: latest
      dockerFilePath:
        required: true
        type: string
      buildPath:
        required: true
        type: string
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Build the Docker image
      run: |
        docker build ${{ inputs.buildPath }} --file ${{ inputs.dockerFilePath }} --tag ${{ inputs.imageName }}:${{ inputs.imageTag }}
        docker push ${{ inputs.imageName }}:${{ inputs.imageTag }}
