name: CD for Frontend
on: 
  workflow_dispatch:
  workflow_call:
  push:
      branches:
        - main
        - stage

jobs:
  build-and-push-image:
    name: Build and Push Docker Image Frontend
    uses: ./.github/workflows/module-docker-image-build-push.yml
    permissions:
      contents: read
      packages: write
      attestations: write
      id-token: write
    with:
      imageName: rateit-frontend
      imageTag: ${{ github.ref_name== 'refs/heads/main' && 'latest' || 'stage' }}
      dockerFilePath: frontend/Dockerfile
      buildPath: frontend
