name: CI for Frontend
on: 
  workflow_dispatch:
  workflow_call:
  pull_request:
    branches:
      - main
      - stage


jobs:
  api-test:
    name: Frontend Test
    permissions:
      checks: write
    uses: ./.github/workflows/module-angular-test.yml
    secrets: inherit
    with:
      projectRoot: frontend
      projectName: Frontend
