name: Java Build and Test using gradle
on:
  workflow_call:
    inputs:
      projectRoot:
        required: true
        type: string
  workflow_dispatch:
    inputs:
      projectRoot:
        required: true
        type: string
jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Set up JDK 21
        uses: actions/setup-java@v2
        with:
          distribution: 'temurin'
          java-version: '21'
      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4
      - name: chmod Gradlew
        run: chmod +x gradlew
        working-directory: ${{ inputs.projectRoot }}
      - name: Test with Gradle
        run: ./gradlew test --no-daemon
        working-directory: ${{ inputs.projectRoot }}
      # generates coverage-report.md and publishes as checkrun
      - name: JaCoCo Code Coverage Report
        id: jacoco_reporter
        uses: PavanMudigonda/jacoco-reporter@v5.0
        with:
          coverage_results_path: ${{ inputs.projectRoot }}/build/reports/jacoco/jacocoTestReport.xml
          coverage_report_name: Coverage
          coverage_report_title: JaCoCo
          github_token: ${{ secrets.GITHUB_TOKEN }}
          skip_check_run: false
          minimum_coverage: 80
          fail_below_threshold: false
          publish_only_summary: false

