name: CD Stage
on: 
  workflow_dispatch:
  workflow_call:
  push:
      paths:
        - 'api/**'
        - 'frontend/**'
      branches:
        - stage

jobs:
  build-and-push-image-api:
    name: Build and Push Docker Image API
    uses: ./.github/workflows/module-docker-image-build-push.yml
    permissions:
      contents: read
      packages: write
      attestations: write
      id-token: write
    with:
      imageName: rateit-api
      imageTag: stage
      dockerFilePath: api/docker/Dockerfile
      buildPath: api    
  build-and-push-image-frontend:
        name: Build and Push Docker Image Frontend
        uses: ./.github/workflows/module-docker-image-build-push.yml
        permissions:
          contents: read
          packages: write
          attestations: write
          id-token: write
        with:
          imageName: rateit-frontend
          imageTag: stage
          dockerFilePath: frontend/Dockerfile
          buildPath: frontend
  update-frontend-deployment-image:
        needs:  [build-and-push-image-frontend, build-and-push-image-api]
        name: Update Deployment Image Tag
        runs-on: ubuntu-latest
        steps:
          - name: Checkout repository
            uses: actions/checkout@v4
          - name: Update Deployment Image Tag
            run: |
              echo "Updating Deployment Image Tag"
              sed -i "s|rateit-frontend.*|rateit-frontend@${{needs.build-and-push-image-frontend.outputs.imageDigest}}|g" infrastructure/kubernetes/staging/frontend-deployment-patch.yaml
              sed -i "s|rateit-frontend.*|rateit-frontend@${{needs.build-and-push-image-frontend.outputs.imageDigest}}|g" infrastructure/kubernetes/production/frontend-deployment-patch.yaml
              sed -i "s|rateit-api.*|rateit-api@${{needs.build-and-push-image-api.outputs.imageDigest}}|g" infrastructure/kubernetes/staging/api-deployment-patch.yaml
              sed -i "s|rateit-api.*|rateit-api@${{needs.build-and-push-image-api.outputs.imageDigest}}|g" infrastructure/kubernetes/production/api-deployment-patch.yaml
              git add infrastructure/kubernetes/staging/frontend-deployment-patch.yaml
              git commit -m "Update Deployment Image Tag"
              git push
          