name: PR Build and Push Docker Images
on: 
  workflow_dispatch:
  workflow_call:
  pull_request:
      branches:
        - stage

jobs:
  build-and-push-image-api:
    name: Build and Push Docker Image API
    uses: ./.github/workflows/module-docker-image-build-push.yml
    permissions:
      contents: read
      packages: write
      attestations: write
      id-token: write
    with:
      imageName: rateit-api
      imageTag: pr-${{ github.event.pull_request.number }}
      dockerFilePath: api/docker/Dockerfile
      buildPath: .
  build-and-push-image-frontend:
        name: Build and Push Docker Image Frontend
        uses: ./.github/workflows/module-docker-image-build-push.yml
        permissions:
          contents: read
          packages: write
          attestations: write
          id-token: write
        with:
          imageName: rateit-frontend
          imageTag: pr-${{ github.event.pull_request.number }}
          dockerFilePath: frontend/Dockerfile
          buildPath: .
  comment-on-pr:
        needs:  [build-and-push-image-frontend, build-and-push-image-api]
        name: Comment on PR
        runs-on: ubuntu-latest
        permissions:
          pull-requests: write
        steps:
          - name: Checkout repository
            uses: actions/checkout@v4
          - name: Comment on PR
            uses: marocchino/sticky-pull-request-comment@v2
            with:
              header: 'Docker Image Digest'
              recreate: true
              message: |
                Docker images have been built and pushed successfully.
                API Image: `${{needs.build-and-push-image-api.outputs.image}}`
                API Image Digest: `${{needs.build-and-push-image-api.outputs.imageDigest}}`
                Frontend Image: `${{needs.build-and-push-image-frontend.outputs.image}}`
                Frontend Image Digest: `${{needs.build-and-push-image-frontend.outputs.imageDigest}}`
